; PlatformIO Project Configuration File
; ESP32-C3 LED Star Controller

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.partitions = min_spiffs.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Библиотеки
lib_deps = 
    makuna/NeoPixelBus@^2.7.9
    bblanchon/ArduinoJson@^7.0.0

; Настройки сборки
build_flags = 
    -DLED_PIN=3
    -DNUM_LEDS=20

; Настройки монитора
monitor_filters = 
    esp32_exception_decoder
    time

; OTA окружение
[env:ota]
extends = env:esp32c3
upload_protocol = espota
upload_port = 192.168.1.252
; upload_flags = 
;     --port=3232
